import { Page, Locator } from '@playwright/test';

/**
 * LoginPage — Page Object Model
 *
 * This class was generated by GitHub Copilot using the prompt:
 * "Write a Playwright page object model class for a login page with
 *  email, password, login button, and error message locators."
 *
 * Demonstrates: SS#3, SS#4, SS#6 in the video
 */
export class LoginPage {
  readonly page: Page;
  readonly usernameInput: Locator;
  readonly passwordInput: Locator;
  readonly loginButton: Locator;
  readonly errorMessage: Locator;
  readonly flashMessage: Locator;

  constructor(page: Page) {
    this.page = page;
    this.usernameInput = page.locator('#username');
    this.passwordInput = page.locator('#password');
    this.loginButton = page.getByRole('button', { name: 'Login' });
    this.errorMessage = page.locator('.flash.error');
    this.flashMessage = page.locator('.flash');
  }

  async goto() {
    await this.page.goto('/login');
  }

  async login(username: string, password: string) {
    await this.usernameInput.fill(username);
    await this.passwordInput.fill(password);
    await this.loginButton.click();
  }

  async getFlashMessageText(): Promise<string> {
    return await this.flashMessage.innerText();
  }
}
